### PR TITLE
do not support block handling in element define method [fix #112]

### LINKED ISSUE #112: Dsl#element should change its block behavior
```ruby
def element(name, options = {}, &block)
  ...
  define_method name do |&block|
    ElementProxy.new(klass, self, options, &block)
  end
  ...
end
```

`Dsl#element` defines a method that gives you an `ElementProxy`. The way this is written is misleading as to its behavior. If you pass a block to the defined method, it is never called or used. For instance, the below code will not throw:

```ruby
element :some_element do
  element :nested
end

some_element do { throw Exception }
```

My proposal is that we make this less misleading as we have seen an instance of passing a block thinking that assertions within the block would be ran and the parameter passed would be the page object:

```ruby
element :page_object do
  element :other_element
  def is_awesome?
    false
  end
end
  
some.really.nested.page_object do |page_object|
  assert page_object.other_element.present?
  assert page_object.is_awesome?
end
```

The block will never be called and the test will silently pass.

There are two thoughts to this fixing this: either define_method creates a method that does not take a parameter which will hopefully not give the impression that giving a block will do something useful, or allow passing a block and call that block with an instance of that `ElementProxy`.

The latter option might look something like this:

```ruby
define_method name do |&block|
  elem = ElementProxy.new(klass, self, options, &block)
  if block
    block.call(elem)
  else
    elem
  end
end
```

### PR DESCRIPTION
**Pull request by ipmsteven**

### CODE REVIEW

File: lib/ae_page_objects/core/dsl.rb [hunk 1]
```diff
@@ -20,7 +20,9 @@ def element(name, options = {}, &block)
 
       self.element_attributes[name.to_sym] = klass
 
-      define_method name do |&block|
+      define_method name do |&block_for_define_method|
+        raise ArgumentError, "Cannot pass block to #{name}" if block_for_define_method
+
         ElementProxy.new(klass, self, options, &block)
```
Comment (dtognazzini) [inline lib/ae_page_objects/core/dsl.rb]: This is wrong. Before `block` referenced the variable local to the define_method block, but now it's referencing the parameter to `element`.

File: lib/ae_page_objects/core/dsl.rb [hunk 2]
```diff
@@ -20,7 +20,9 @@ def element(name, options = {}, &block)
 
       self.element_attributes[name.to_sym] = klass
 
-      define_method name do |&block|
+      define_method name do |&block_for_define_method|
```
Comment (dtognazzini) [inline lib/ae_page_objects/core/dsl.rb]: Why accept a block and then assert that it's not passed? An easier implementation is to remove the parameter entirely.

File: lib/ae_page_objects/core/dsl.rb (hunk 1 above)
Comment (ipmsteven) [inline lib/ae_page_objects/core/dsl.rb]: @dtognazzini oh, yeah, I forgot to remove the `&block` here

File: lib/ae_page_objects/core/dsl.rb (hunk 2 above)
Comment (ipmsteven) [inline lib/ae_page_objects/core/dsl.rb]: @dtognazzini  I think the purpose it that if the user of aepos pass a block, the method should throw exception to notify the use that he cannot pass block to it

Comment (dtognazzini) [inline lib/ae_page_objects/core/dsl.rb]: Why? In Ruby, you can pass a block to *any* method. Should every method that does not do anything with the block raise an exception?

Comment (ipmsteven) [inline lib/ae_page_objects/core/dsl.rb]: @dtognazzini 
I think raising an exception when passing a block is more conservative, that help developer to find the wrong usage of a method.

For example, an exception will be thrown if developer write code like this:

```ruby
element :some_element do
  element :nested
end

some_element do { |e| e.text == 'xxx' }
```

Since in Ruby you can pass a block to any method, that doesn't make sense to raise an exception for every method that does not do anything with the block. 

Maybe we can only do the raise exception thing for the methods that may let developer think it can accept block but not? 
like `visit` method(https://github.com/appfolio/ae_page_objects/blob/master/lib/ae_page_objects/concerns/visitable.rb#L25)?

Comment (dtognazzini) [inline lib/ae_page_objects/core/dsl.rb]: The handling in `visit` should be removed as well. That code is an artifact of when this gem was private and we were transitioning from one style to another. The `raise` should have been removed before open sourcing the gem.

In your example, the following is valid and the block is handled and defines a [nested element](https://github.com/appfolio/ae_page_objects/tree/130b710b85fcc95e2e2d03fe2f95feb21331ebcd#nested-elements):
```ruby
element :some_element do
  element :nested
end
```

>Since in Ruby you can pass a block to any method, that doesn't make sense to raise an exception for every method that does not do anything with the block.

So, you agree?

Comment (ipmsteven) [inline lib/ae_page_objects/core/dsl.rb]: @dtognazzini  the block passed to `element :some_element` is handled, how about the block passed to `some_element` method?  `some_element do { |e| e.text == xxx' }`

Comment (dtognazzini) [inline lib/ae_page_objects/core/dsl.rb]: Yes, if the developer write that code the block is never called just like any other Ruby method.

Comment (ipmsteven) [inline lib/ae_page_objects/core/dsl.rb]: @dtognazzini 
ok, I am fine with just remove the block handling without throwing exception if a block is passed, just feel that it's so easy to pass block which contains the assertion test by mistake(the test just pass since it never run :cry: ) maybe that case should be handled by developer not by aepos.
